### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by egpro** [bigman212/Django-Fogstream#1]
https://github.com/bigman212/Django-Fogstream/blob/2aa3c93f6eb89b7d391937e09b9dc9240e0541af/library_app/models.py#L7

В моделях необходимо:
1. Указывать мета информацию, такую как стровое представление в ```verbose_name```
2. Необходимо определять метод ```__str__```, для того, чтобы наши инстансы модели выглядели красиво
3. В каждом поле первым параметром необходимо задавать ```verbose_name``` , для читаемого отображения в админке
4. Не обязательно задавать ```primary_key```, Django создаст за нас ключевое поле
5. Когда задаем поле типа внешний ключ, рекомендуется задавать еще и ```related_name```
6. Задавать метод ```get_books``` плохая практика, у нас есть связанные поля, можно реализовать связь через ник

**Comment by bigman212** [comment]
Refactored, added verbose names.
